default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: my_profile

test:
  <<: *default
  database: appname_test

production:
  database: my_profile
  username: root
  password: root
  adapter: postgresql
  encoding: unicode
  pool: 5

